package ffi

/*
#include "../../deps/signal_ffi.h"
#include "../../deps/signal_ffi_testing.h"
#include <stdlib.h>
#cgo LDFLAGS: -L${SRCDIR}/../../deps -lsignal_ffi -ldl -lpthread -lm -lstdc++
*/
import "C"

/*
SignalFfiError* signal_authenticated_chat_connection_clear_push_token(
SignalFfiError* signal_authenticated_chat_connection_clear_registration_lock(
SignalFfiError* signal_authenticated_chat_connection_confirm_username(
SignalFfiError* signal_authenticated_chat_connection_connect(
SignalFfiError* signal_authenticated_chat_connection_delete_username_hash(
SignalFfiError* signal_authenticated_chat_connection_delete_username_link(
SignalFfiError* signal_authenticated_chat_connection_destroy(
SignalFfiError* signal_authenticated_chat_connection_disconnect(
SignalFfiError* signal_authenticated_chat_connection_get_devices(
SignalFfiError* signal_authenticated_chat_connection_get_upload_form(
SignalFfiError* signal_authenticated_chat_connection_info(
SignalFfiError* signal_authenticated_chat_connection_init_listener(
SignalFfiError* signal_authenticated_chat_connection_preconnect(
SignalFfiError* signal_authenticated_chat_connection_redeem_backup_receipt(
SignalFfiError* signal_authenticated_chat_connection_remove_device(
SignalFfiError* signal_authenticated_chat_connection_reserve_username_hash(
SignalFfiError* signal_authenticated_chat_connection_send(
SignalFfiError* signal_authenticated_chat_connection_send_message(
SignalFfiError* signal_authenticated_chat_connection_send_raw_grpc(
SignalFfiError* signal_authenticated_chat_connection_send_sync_message(
SignalFfiError* signal_authenticated_chat_connection_set_device_name(
SignalFfiError* signal_authenticated_chat_connection_set_discoverable_by_phone_number(
SignalFfiError* signal_authenticated_chat_connection_set_push_token_apns(
SignalFfiError* signal_authenticated_chat_connection_set_registration_lock(
SignalFfiError* signal_authenticated_chat_connection_set_registration_recovery_password(
SignalFfiError* signal_authenticated_chat_connection_set_username_link(
*/
